### ISSUE TITLE
Traffic collection does not work on ACX7100 22.4R2.11-EVO

### ISSUE THREAD

**Issue by Jimmy-Cl** [door7302/openjts#15]
We have a fleet of ACX7100 (48L and 32C) that currently use 22.4R2.11-EVO (Current JTAC recommend image) and traffic collection is not working. Using the path browser it looks like they use a different path which prepends some sensors with an if_. See the below outputs from one of the ACX7100s on 22.4R2.11-EVO and our Lab ACX7100 on 23.2R2.21-EVO.

ACX7100 on 22.4R2.11-EVO -

![image](https://github.com/door7302/openjts/assets/68513176/58d45f27-db3b-44f3-b1a0-f39d8f4aacc5)

ACX7100 on 23.2R2.21-EVO - 

![image](https://github.com/door7302/openjts/assets/68513176/3a501657-8112-4627-b941-8da850a722e9)

I created a fork and tried adding the following lines to acx_traffic.conf but had no luck, I think it could be something to do with the older firmware also using if_name=* for these and not just name=* but I'm not sure.

    [[processors.rename.replace]]
    field="counters/if_in_octets"
    dest="in_octets"

    [[processors.rename.replace]]
    field="counters/if_out_octets"
    dest="out_octets"

    [[processors.rename.replace]]
    field="counters/if_in_pkts"
    dest="in_pkts"

    [[processors.rename.replace]]
    field="counters/if_out_pkts"
    dest="out_pkts"

Let me know if you might have come across anything like this before or have any ideas as we are keen to start streaming telemetry out of our ACXs. Also please reach out if you would like us to do any tests as we are happy to help out. :)

**Comment by door7302** [comment]
Hello. 

Thank you for this feedback and the issue. Let me check in my lab with your current version. I get back to you soon.

david

**Comment by Jimmy-Cl** [comment]
Hi David,

Thanks for getting back to me.

I think I found the issue and it was related to the interfaces using if_name=* instead of just using name=*. 
I fixed it by adding the following lines to my acx_traffic.conf

    [[processors.rename.replace]]
    tag="/interfaces/interface/if_name"
    dest="if_name"

    [[processors.rename.replace]]
    tag="/interfaces/interface/@if_name"
    dest="if_name"

    [[processors.rename.replace]]
    field="counters/if_in_octets"
    dest="in_octets"

    [[processors.rename.replace]]
    field="counters/if_out_octets"
    dest="out_octets"

    [[processors.rename.replace]]
    field="counters/if_in_pkts"
    dest="in_pkts"

    [[processors.rename.replace]]
    field="counters/if_out_pkts"
    dest="out_pkts"

I'll put it into a pull request tomorrow so you can look at the changes and test the new config on your lab ACX.

James

**Comment by door7302** [comment]
I'm suprised in my lab with this ACX:

Model: ACX7100-48L
Junos: 22.4R2.11-EVO
Yocto: 3.0.2
Linux Kernel: 5.2.60-yocto-standard-g5039935
JUNOS-EVO OS 64-bit [junos-evo-install-acx-f-x86-64-22.4R2.11-EVO]

I didn't see the same behavior. 

<img width="1127" alt="image" src="https://github.com/door7302/openjts/assets/23736344/bae0ca86-2379-49fc-9c09-25c80a1f52be">

**Comment by door7302** [comment]
thank you for the output... It's weird. Let me ask some guys internally and come back to you soon.

**Comment by door7302** [comment]
Ok. This was a limitation in 22.4 that was fixed later to align QFX/ACX Interface counters with the OpenConfig models. I will fix the profile in OpenJTS 1.0.1 which should be published tomorrow. I'm going to close your PR as the patched version will include the fix with other minor fixes. I keep the issue opened til you've made some tests.

**Comment by door7302** [comment]
I published the v1.0.1. JTSO has also been updated. Please refer to the "update stack" part in the README. Let me know if it works better. Thks
