### ISSUE TITLE
Implement "common" configs

### ISSUE THREAD

**Issue by Olen** [door7302/openjts#17]
After just having a quick look at the `jtso/profiles/` it feels like it could make sense to have a `common.conf` with default elements, that is inherited by all the platform specific configs.  Settings in the platform/version specific configs should of course overwrite the common config.

The difference between e.g, `ptx_health.conf` and `mx_health.conf` is only two lines (which maybe even should have been in the ptx-config? - I haven't checked if they are avalilable for ptx/acx)
```
@@ -308,6 +307,8 @@
       "linecard_cpu",
       "linecard_memory",
       "buffer_usage",
+        "admin_status",
+        "oper_status",
       "fabric_drops_pkts_rate",
```

Pluss the `enrichfilepath`.

ACX-health has only 6 extra lines, compared with the ptx-config:

``` 
+[[processors.filtering]]
+  order = 4
+  [[processors.filtering.tags]]
+     key = "if_name"
+     pattern = "^(et-|xe-|ge-).*"
+     Action = "accept"
```

By adding a "common.conf" for all the shared stuff, it would significantly lower the bar for creating new profiles, and hopefully you would get some PRs to fix #11

**Comment by door7302** [comment]
Thank you for your feedback... will add this enhancement in the next release. Moreover, in the next release, I will provide a guide to let anyone create his own profile. 

I plan to deliver the next release in a few weeks. 

David

**Comment by Olen** [comment]
Great!
And thank you for (what looks like) an excellent tool.  Have not tested it yet, since I only have SRX and EX to test it with right now...

If/when I get it up and running, I'll try to add some PRs for things I miss.

**Comment by door7302** [comment]
I've planned one patch (release 1.0.2) this week to add a few enhancements. But I scheduled in several weeks to add more platforms and your suggestion in release 1.1.0

stay tuned :) and thanks for your contribution

**Comment by door7302** [comment]
Will be supported with 1.1.0
