### ISSUE TITLE
How to change Sample Interval for Telemetry Stats of Routers in JTS

### ISSUE THREAD

**Issue by arbabali999** [door7302/openjts#22]
I am unable to change sample interval Telemetry Stats of Routers in JTS. I want to modify it to 5s.

**Comment by door7302** [comment]
The next release will provide the ability to configure the streaming rate. As of now it is enforced in the profile configuration

**Comment by akashm70** [comment]
can we change the streaming rate to less than a 1s to monitor interface burst at msec level.
