### ISSUE TITLE
 VMHost RE 0 Disk 1 Write Rate Threshold Cross

### ISSUE THREAD

**Issue by cadi455** [door7302/openjts#23]
Hello,

I have implemented OpenJTS on my network (MX960 version JUNOS 21.4R3-S4.9). After six hours, an alarm was triggered:

show system alarms
2 alarms currently active
Alarm time        Class Description
2024-04-30 05:49:14 CET Minor VMHost RE 1 Disk 1 Write Rate Threshold Cross
2024-04-30 01:14:45 CET Minor VMHost RE 0 Disk 1 Write Rate Threshold Cross
Two minor alarms are currently active, indicating that the write rate to disk 1 has exceeded the threshold for VMHost RE 1 and RE 0.

What can I do to resolve this issue?

**Comment by nguyenduchoa37** [comment]
You mean fix the issue on MX ?

**Comment by door7302** [comment]
It seems you subscribed to an unsupported path. Could you please share the profile you used? thanks

**Comment by cadi455** [comment]
i used this profile for MX960 version 21.4R3-S4.9: traffic ; optic ; power ; filter ; health ; bgp.
Thank you for your support.
