### ISSUE TITLE
Unable to install OpenJTI in docker. Kapacitor mkdir /var/log/kapacitor: permission denied

### ISSUE THREAD

**Issue by ivanovuri** [door7302/openjts#33]
Hi, my system is:

> cat /etc/os-release 
> PRETTY_NAME="Ubuntu 22.04.4 LTS"
> NAME="Ubuntu"
> VERSION_ID="22.04"
> VERSION="22.04.4 LTS (Jammy Jellyfish)"

After performing simple installation kapacitor can't start:
> 2024/05/31 14:38:47 Using configuration at: /etc/kapacitor/kapacitor.conf
> ts=2024-05-31T14:38:47.969Z lvl=error msg="encountered error" service=run err="failed to open diagnostic service: mkdir /var/log/kapacitor: permission denied"
> run: failed to open diagnostic service: mkdir /var/log/kapacitor: permission denied

Changing volume path to leads to same error:
>     volumes:
>      - ./kapacitor/var/log:/var/log

Commenting volume path in such a way:
>    volumes:
>      #      - ./kapacitor/var/log:/var/log
>     - ./kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf
>    - ./kapacitor/data:/var/lib/kapacitor

leads to another error:
> 2024/05/31 14:50:35 Using configuration at: /etc/kapacitor/kapacitor.conf
> run: create server: failed to save cluster ID: open /var/lib/kapacitor/cluster.id: permission denied

Any help would be greatly appreciated.

**Comment by Roysoldier** [comment]
Hello. Just for testing purpose Did you try to launch the "compose" in root?

**Comment by ivanovuri** [comment]
Hello, yes many different way without luck.
But I found the issue, It a pity project leader don't
