### ISSUE TITLE
Version on the home page

### ISSUE THREAD

**Issue by arraisfilho** [door7302/openjts#34]
Hi,

I think the home page has a bug in the version, I recently installed it and it appears as version 1.0.1

`JTS Version - 1.0.1 - JTSO Version 1.0.1 - JTS Telegraf N/A`

Regards.

**Comment by Roysoldier** [comment]
Indeed. Let me check and fix it. Thank you for your feedback. I'll keep you update.

**Comment by door7302** [comment]
Just fixed. thanks
