### ISSUE TITLE
Open JTS with native Telemetry

### ISSUE THREAD

**Issue by nguyenduchoa37** [door7302/openjts#36]
Hi all.

I already install JTS and also have some tests with MX/vMX/ACX. May I know JTS is support for gRPC streaming Telemetry, so how about Telemetry over UDP ? I mean the Through UDP from so-called native sensors that export data close to the source, such as the line card or network processing unit (NPU).

**Comment by door7302** [comment]
Hello. JTS doesn't support UDP-based telemetry. Native sensors can be requested by gRPC/gNMI if needed. If you want, I could create a dedicated profile for that. Please share sensor paths you are interested in.

**Comment by nguyenduchoa37** [comment]
Hi.

As I understand, native sensors data should be sent by FPC. If requested by gRPC/gNMI it could be congestion for FXP0 or congested for Routing Engine ?

**Comment by door7302** [comment]
I tested high volume of telemetry data over fxp0 without any issue.

**Comment by nguyenduchoa37** [comment]
> I tested high volume of telemetry data over fxp0 without any issue.

OKie thank.

**Comment by nguyenduchoa37** [comment]
> Hello. JTS doesn't support UDP-based telemetry. Native sensors can be requested by gRPC/gNMI if needed. If you want, I could create a dedicated profile for that. Please share sensor paths you are interested in.

Could you create profile with this sensor
/junos/system/linecard/qmon/
https://www.juniper.net/documentation/us/en/software/junos/cli-reference/topics/ref/statement/sensor-edit-services-analytics.html
