### ISSUE TITLE
Push hardware information to OpenJTS

### ISSUE THREAD

**Issue by nguyenduchoa37** [door7302/openjts#39]
Hi.

I install OpenJST to monitor MX960 with profile Heal Monitoring Profile. I make a test by shutting down FPC on MX960 (using the command request fpc slot <X> offline). But I cannot see any alarm or warning on Grafara Web Gui (up to 4-5 minutes). Is there any way to detect fast the hardware error with OpenJTS?

**Comment by door7302** [comment]
Hello, 

Could you please share the Junos version and the model of card.

David

**Comment by nguyenduchoa37** [comment]
> Hello,
> 
> Could you please share the Junos version and the model of card.
> 
> David

Hi.

I test with MX960 Junos: 20.4R3-S8.1, using MPC10E. But if this error appears on Grafana, which kind of this log ? And how many seconds this log will exist since that card is down on box?

**Comment by door7302** [comment]
I believe manually shutting down an MPC is not considered an error. If you want, I could provide you a command to simulate an HW error in your lab.

**Comment by nguyenduchoa37** [comment]
Yes, please share me that command. Anw, so if I unplug fpc, it's ok for
testing?

**Comment by door7302** [comment]
FOR LAB ONLY 

start shell pfe network fpcX.0    <<< X = slot number 
 
show cmerror module   <<<< Identify the module ID for “Storage device” - in my case this is 5

show cmerror module 5 

Error-id     PFE  Level  Threshold  Count  Occured  Cleared  Last-occurred(ms ago)  Name
------------------------------------------------------------------------------------------
0x2c0002      0   Major      1        0       0        0        0                   CPU_CMERROR_STORAGE_MSATA_DISABLED
0x2c0001      0   Minor      1        0       0        0        0                   CPU_CMERROR_STORAGE_SMARTD_ERROR
0x2c0003      0   Minor      1        0       0        0        0                   CPU_CMERROR_STORAGE_ACCESS_ERROR

Note, the hexa ERROR-ID of MAJOR error and its description and simulate the Error: 

test cmerror trigger-error 0x2c0002 0 CPU_CMERROR_STORAGE_MSATA_DISABLED 5    

exit 

Now you should see a MAJOR ALARM 

regress@rtme-mx-25> show chassis alarms 
3 alarms currently active
Alarm time               Class  Description
2024-06-28 06:30:54 PDT  Major  FPC 2 Major Errors

On openJTS you should see:

![image](https://github.com/door7302/openjts/assets/23736344/7678b833-85f2-4295-a9ca-169676761965)


To clear the alarm you need to reboot

**Comment by nguyenduchoa37** [comment]
Sorry for the late reply due to missing your email.

I will test and update you soon.

**Comment by door7302** [comment]
Any updates?

**Comment by nguyenduchoa37** [comment]
The result is as expected.





***@***.***_AGG02_TEST_SRT_ZTE> show chassis alarms    3 alarms currently
activeAlarm time               Class  Description2024-08-08 09:39:27 +07
 Major  FPC 2 Major Errors2024-08-07 13:57:16 +07  Minor  CB 0
Removed2024-08-05 14:19:29 +07  Minor  Backup RE Active*

But may I know which mechanism that Grafana can show this error ? Still
streaming via gRPC? Because I see the notification does not appear
immediately, it still need a time to refresh.
*Thanks Regard*
*Nguyen Duc Hoa (Mr)*



Vào Th 5, 8 thg 8, 2024 vào lúc 00:01 David Roy ***@***.***>
đã viết:
