### ISSUE TITLE
POWER MONITORING - POSSIBLE BUG MX204

### ISSUE THREAD

**Issue by arraisfilho** [door7302/openjts#40]
Hi,

The power data is not being shown, the only information that appears is the **CB0 Used Power** and the temperature of the **Routing Engine0**, however, serrated. I have two boxes with different versions of Junos (20.4R3.8 and 21.4R3-S6.5) and both the behavior is the same.

<img width="1487" alt="Captura de Tela 2024-06-25 às 11 54 28" src="https://github.com/door7302/openjts/assets/19312891/883fef96-39d1-4573-bf0a-590fc73e53b9">

By using the Browser menu and querying **/components/component/**, I see that most of the information has the **false** flag, however, the data on mode and version are available, even so they do not appear in the graph. In MX204 this data is not exported?

Using JTS 1.0.7.

**Comment by door7302** [comment]
Thank you for your feedback. I will try to replicate in my lab and fix it. I will keep you updated soon.

**Comment by door7302** [comment]
Hello v1.0.8 fixes this issue. Note: MX204 provides only few KPI related to environment (due to few HW sensors on this platform)  

BR
David
