### ISSUE TITLE
Implement unit/subinterface traffic counters

### ISSUE THREAD

**Issue by brevius** [door7302/openjts#43]
Hi,

Your approach (grpc) seems to be quite promising  when I compare it to my old GPB based solution especially thanks to the enrichment functionality which adds interfaces descriptions. However is it possible to implement in similar way unit/sub-interface counters?

**Comment by door7302** [comment]
Hello, this is planned to enhance the Traffic profile to support both physical and logical traffic. I'm going to prioritize this.. and I will update you soon

**Comment by door7302** [comment]
Please have a look at the release 1.0.9. Please follow the upgrade procedure here: https://github.com/door7302/openjts/releases/tag/v1.0.9 

<img width="1725" alt="Screenshot 2024-07-18 at 11 53 19" src="https://github.com/user-attachments/assets/32162537-222b-499f-a836-e1b273c54103">
<img width="1720" alt="Screenshot 2024-07-18 at 11 53 38" src="https://github.com/user-attachments/assets/bad4bcfe-df53-4f1d-bd09-69afae73f611">
