### ISSUE TITLE
error on build 1.0.9 version

### ISSUE THREAD

**Issue by guilhermefigueiredo** [door7302/openjts#46]
hello, i have this error on build new version:

docker-compose build --no-cache
influxdb uses an image, skipping
kapacitor uses an image, skipping
grafana uses an image, skipping
Building telegraf_vmx
Sending build context to Docker daemon  20.66MB
Step 1/15 : FROM golang:alpine as builder
 ---> a60a31a97fdb
Step 2/15 : ARG LDFLAGS=""
 ---> Running in 98a9ecd02426
Removing intermediate container 98a9ecd02426
 ---> d66cadedabef
Step 3/15 : ARG VERSION="1.0.5"
 ---> Running in 3c95441e03f8
Removing intermediate container 3c95441e03f8
 ---> f8c3020fe99e
Step 4/15 : RUN apk --update --no-cache add git build-base gcc
 ---> Running in eb8883af411d
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/main: temporary error (try again later)
WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/community: temporary error (try again later)
ERROR: unable to select packages:
  build-base (no such package):
    required by: world[build-base]
  gcc (no such package):
    required by: world[gcc]
  git (no such package):
    required by: world[git]
The command '/bin/sh -c apk --update --no-cache add git build-base gcc' returned a non-zero code: 3
ERROR: Service 'telegraf_vmx' failed to build : Build failed

docker image ls
REPOSITORY          TAG           IMAGE ID       CREATED          SIZE
<none>              <none>        f8c3020fe99e   2 minutes ago    231MB
<none>              <none>        1c6ba35b3794   15 minutes ago   231MB
golang              alpine        a60a31a97fdb   2 weeks ago      231MB
alpine              latest        a606584aa9aa   3 weeks ago      7.8MB
golang              <none>        288827cf059e   4 weeks ago      231MB
influxdb            1.8           0067f69032c8   5 weeks ago      307MB
chronograf          latest        78c17d602445   2 months ago     236MB
kapacitor           1.7           89b8dd6c94dd   2 months ago     331MB
grafana/grafana     10.3.1        2fec87cd4362   5 months ago     406MB
phusion/baseimage   focal-1.2.0   99244e721357   2 years ago      225MB
telegraf            1.7           e58ff0b8f73c   5 years ago      212MB
kapacitor           1.5.0         4ff381f009fc   6 years ago      253MB
juniper/pyez        2.1.8         09a523c2b46b   6 years ago      281MB
juniper/pyez        2.0.1         e61c159ee89f   7 years ago      93MB

**Comment by door7302** [comment]
Hello, I tried on a fresh VM and it worked for me. I have these versions for docker and docker compose :

# docker --version 
Docker version 23.0.6, build ef23cbc
# docker compose version 
Docker Compose version v2.17.3

Could you try to update your docker / compose ? 
David

**Comment by guilhermefigueiredo** [comment]
i will try to update my docker, im running version 20 from docker and 1.29 from composer

root@graylog:~# docker --version
Docker version 20.10.24+dfsg1, build 297e128
root@graylog:~# docker-compose --version
docker-compose version 1.29.2, build unknown

**Comment by guilhermefigueiredo** [comment]
i make the docker upgrade but i no have success:

ii  docker-ce                         5:27.0.3-1~debian.11~bullseye           amd64        Docker: the open-source application container engine
ii  docker-ce-cli                     5:27.0.3-1~debian.11~bullseye           amd64        Docker CLI: the open-source application container engine
ii  docker-ce-rootless-extras         5:27.0.3-1~debian.11~bullseye           amd64        Rootless support for Docker.
ii  docker-compose-plugin             2.28.1-1~debian.11~bullseye             amd64        Docker Compose (V2) plugin for the Docker CLI.

root@graylog:/home/openjts/openjts/compose# docker compose build --no-cache
WARN[0000] /home/openjts/openjts/compose/docker-compose.yml: `version` is obsolete 
[+] Building 24.0s (8/27)                                                                                                                                                                                                                                                    docker:default
 => [telegraf_vmx internal] load git source https://github.com/door7302/jts_telegraf.git#v1.0.5                                                                                                                                                                                        3.6s
 => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)                                                                                                                                                                                                         3.6s
 => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)                                                                                                                                                                                                         3.6s
 => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)                                                                                                                                                                                                         3.6s
 => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)                                                                                                                                                                                                         3.6s 
 => [jtso internal] load git source https://github.com/door7302/jtso.git#v1.0.4                                                                                                                                                                                                        2.7s 
 => [telegraf_ptx internal] load metadata for docker.io/library/alpine:latest                                                                                                                                                                                                          1.9s 
 => [telegraf_acx internal] load metadata for docker.io/library/golang:alpine                                                                                                                                                                                                          2.0s 
 => [telegraf_vmx stage-1 1/4] FROM docker.io/library/alpine:latest@sha256:b89d9c93e9ed3597455c90a0b88a8bbb5cb7188438f70953fede212a0c4394e0                                                                                                                                            1.3s
 => => resolve docker.io/library/alpine:latest@sha256:b89d9c93e9ed3597455c90a0b88a8bbb5cb7188438f70953fede212a0c4394e0                                                                                                                                                                 0.0s
 => => sha256:b89d9c93e9ed3597455c90a0b88a8bbb5cb7188438f70953fede212a0c4394e0 1.85kB / 1.85kB                                                                                                                                                                                         0.0s
 => => sha256:dabf91b69c191a1a0a1628fd6bdd029c0c4018041c7f052870bb13c5a222ae76 528B / 528B                                                                                                                                                                                             0.0s
 => => sha256:a606584aa9aa875552092ec9e1d62cb98d486f51f389609914039aabd9414687 1.47kB / 1.47kB                                                                                                                                                                                         0.0s
 => => sha256:ec99f8b99825a742d50fb3ce173d291378a46ab54b8ef7dd75e5654e2a296e99 3.62MB / 3.62MB                                                                                                                                                                                         0.4s
 => => extracting sha256:ec99f8b99825a742d50fb3ce173d291378a46ab54b8ef7dd75e5654e2a296e99                                                                                                                                                                                              0.5s
 => CANCELED [telegraf_acx builder 1/5] FROM docker.io/library/golang:alpine@sha256:8c9183f715b0b4eca05b8b3dbf59766aaedb41ec07477b132ee2891ac0110a07                                                                                                                                  18.5s
 => => resolve docker.io/library/golang:alpine@sha256:8c9183f715b0b4eca05b8b3dbf59766aaedb41ec07477b132ee2891ac0110a07                                                                                                                                                                 0.1s
 => => sha256:ec99f8b99825a742d50fb3ce173d291378a46ab54b8ef7dd75e5654e2a296e99 3.62MB / 3.62MB                                                                                                                                                                                         0.4s
 => => sha256:8bfb7f89ddd560368de98a53e7fbc004ef3d4bb2ea7e6efbb80992a6f907eed1 292.43kB / 292.43kB                                                                                                                                                                                     0.3s
 => => sha256:32a2f51ff3dde07bfa1ce35b5597b2d97295e64a461d98e696feda7b25a6dc5f 69.35MB / 69.35MB                                                                                                                                                                                       3.2s
 => => sha256:8c9183f715b0b4eca05b8b3dbf59766aaedb41ec07477b132ee2891ac0110a07 10.29kB / 10.29kB                                                                                                                                                                                       0.0s
 => => sha256:4707c052e5bd90c1c6ae16d1825e3ea5076ec1b06de30e34596b1e6f6b9916cf 1.92kB / 1.92kB                                                                                                                                                                                         0.0s
 => => sha256:a60a31a97fdb2c7eac5f46e5ab4cdd6e79fb96e960b520f9574a34fa163fa785 2.09kB / 2.09kB                                                                                                                                                                                         0.0s
 => => extracting sha256:ec99f8b99825a742d50fb3ce173d291378a46ab54b8ef7dd75e5654e2a296e99                                                                                                                                                                                             18.7s
 => => sha256:935834aa092a42930b12249d2899dcc59baac0616accbcd97e672ba7b26c469a 126B / 126B                                                                                                                                                                                             0.6s
 => => sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1 32B / 32B                                                                                                                                                                                               0.6s
 => => extracting sha256:8bfb7f89ddd560368de98a53e7fbc004ef3d4bb2ea7e6efbb80992a6f907eed1                                                                                                                                                                                              0.2s
 => => extracting sha256:32a2f51ff3dde07bfa1ce35b5597b2d97295e64a461d98e696feda7b25a6dc5f                                                                                                                                                                                             15.8s
 => ERROR [telegraf_acx stage-1 2/4] RUN apk update --no-cache &&     adduser -S -D -H -h / telegraf                                                                                                                                                                                  17.9s
 => ERROR [jtso stage-1 2/9] RUN apk update --no-cache                                                                                                                                                                                                                                16.0s
------                                                                                                                                                                                                                                                                                      
 > [telegraf_acx stage-1 2/4] RUN apk update --no-cache &&     adduser -S -D -H -h / telegraf:                                                                                                                                                                                              
0.751 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz                                                                                                                                                                                                         
5.757 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz                                                                                                                                                                                                    
5.757 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/main: temporary error (try again later)                                                                                                                                                                                 
10.76 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/community: temporary error (try again later)                                                                                                                                                                            
10.76 4 unavailable, 0 stale; 14 distinct packages available                                                                                                                                                                                                                                
------                                                                                                                                                                                                                                                                                      
------                                                                                                                                                                                                                                                                                      
 > [jtso stage-1 2/9] RUN apk update --no-cache:                                                                                                                                                                                                                                            
0.684 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
5.689 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
5.689 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/main: temporary error (try again later)
10.69 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/community: temporary error (try again later)
10.69 4 unavailable, 0 stale; 14 distinct packages available
------
failed to solve: process "/bin/sh -c apk update --no-cache" did not complete successfully: exit code: 4

**Comment by door7302** [comment]
Maybe you are behind a proxy or firewall that prevents you from fetching some internet repo to build the image... 
I put the 2 builds for Ubuntu: telegraf and jtso here:

https://drive.google.com/file/d/10ea-L8KlCrtgTo9HmRAdTF82v16JjjB9/view?usp=drive_link
https://drive.google.com/file/d/1qeT5YzaoVq4n8soFTRuVeUfvpRKZTuOd/view?usp=drive_link 

Could you try to download them. Upload to your VM and issue:

docker load --input telegraf.tar
docker load --input jtso.tar

and then try to start the OpenJTS stack from compose folder:

docker compose up -d
 
Hope it will help

**Comment by guilhermefigueiredo** [comment]
I will test in another environment before downloading the file, but I was able to install the old version normally.
I'll let you know.

thanks for all

**Comment by guilhermefigueiredo** [comment]
There really was a firewall that IT didn't inform me about, it's probably the same one that is impacting my Telegraf queries.

Thank you very much for your support!

**Comment by door7302** [comment]
you're welcome.
