### ISSUE TITLE
Ability to sort and filter routers when adding them

### ISSUE THREAD

**Issue by heydolon** [door7302/openjts#5]
1. Ability to sort routers alphabetically when adding them to the `routers` tab makes easy to check if all your routers are added. If by any reason, the first router is not added (e.g. vmx501) when adding all the rest (e.g. vmx502, vmx503, ..., vmx507), vmx501 will be shown the last one.

2. Ability to filter routers from the list by tags. So this will include a tagging ability when adding routers. For example, if adding routers and saying they are ACXs, or MXs, or they belong to East or West, you can easily track if all your expectations are eventually there (e.g. 4 devices from East and 5 from West).

**Comment by door7302** [comment]
will be supported with version 1.1.0

**Comment by door7302** [comment]
will be supported with version 1.1.0
