### ISSUE TITLE
Drop per queue of traffic profile not have data

### ISSUE THREAD

**Issue by dinhphuoc07** [door7302/openjts#50]
I'm using traffic profile to collect interface traffic and drop queue of ports. "Port statistics" is fine but "Drop per queue" not have data (attach image). Has anyone had the same problem and solved it? 
![Screen Shot 2024-08-07 at 10 52 20 PM](https://github.com/user-attachments/assets/7d847719-a49b-4f83-bdd1-bef8a522dbef)
![Screen Shot 2024-08-07 at 10 50 09 PM](https://github.com/user-attachments/assets/990d73a7-d140-4b1a-a0da-75753b9dacfd)

**Comment by door7302** [comment]
hello, if you never experienced "drop" on this interface this behavior is normal. By default on Juniper we have a feature called zero-supression that avoid sending counters with value at 0. If you want to disable this feature - apply this command:

set services analytics zero-suppression no-zero-suppression 

Could try and tell me if you see "0" drops
David

**Comment by dinhphuoc07** [comment]
Hi David,

Thanks for your reply. I configured on router but still not see "0" drops. I send you router model and OS version:
MX960_RE0> show configuration services analytics    
zero-suppression {
    no-zero-suppression;
}

MX960_RE0> show version 
Hostname: MX960
Model: mx960
Junos: 20.4R3-S8.1

![Screenshot 2024-08-08 at 9 25 31 AM](https://github.com/user-attachments/assets/8cb5ea4b-be59-4e94-94c4-57f5392b24d0)
![Screenshot 2024-08-08 at 9 27 15 AM](https://github.com/user-attachments/assets/14a8a740-eeab-4dda-8f6d-5c137692e71f)
![Screenshot 2024-08-08 at 9 27 59 AM](https://github.com/user-attachments/assets/f94d1d1b-4642-4e67-9d9d-17c9f2e56147)

Regards,

**Comment by dinhphuoc07** [comment]
Dear David,
When I configured "zero-suppression", drop queue still No data. But when I shaping rate in class-of-service, packet increase and graph has data. Thanks for your support.
Regards,
