### ISSUE TITLE
Avoid using docker compose images with ":latest" tag

### ISSUE THREAD

**Issue by heydolon** [door7302/openjts#6]
I would suggest to avoid using docker compose images with `:latest` tag since it might happen that people uses openJTS with different versions not working well together (or at least not having tested together!). I would recommend sticking to a specific docker image version in `docker-compose.yml` file, test it and once it is bullet proof, generate a tag of openJTS release with these versions. 

Next release, if you want, test it with a newer version, but if you put `:latest`, depending on when someone pulls the project and install it, might get a different grafana version for example than you expect.

Also... not sure if there is a reason for that, but influxdb v1.8 is quite old. Not sure if there is a specific reason behind it, but there is already v2.7.4. I am running influxdb:2.7.1 in TME Lab.

**Comment by door7302** [comment]
Pb Fixed in the release 1.0.0
