### ISSUE TITLE
Removing devices from routers list does not remove them from Grafana variables

### ISSUE THREAD

**Issue by heydolon** [door7302/openjts#7]
When removing a device from the routers list, the router is not being removed from the Grafana variables, so it still shows up in the list of available devices to monitor it its profile.

<img width="1728" alt="Screenshot 2023-12-18 at 15 40 30" src="https://github.com/door7302/openjts/assets/38101374/d6bdfd78-5a8d-4dab-95f4-3691c4e208d1">

**Comment by door7302** [comment]
Enhancement implemented in release 1.0.0
